routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('/', function () {
	$menus = \App\Menu::all();
    return view('main', compact('menus'));


});

Route::get('contact', function(){
	return view('contacts.index');
});

Route::resource('/clients', 'ClientController');

Route::resource('/menus', 'MenuController');

Route::resource('/form', 'FormController');


Route::get('kategorijos', function(){
	return view('category');
});

Route::get('login', function(){
	return views('auth.login');
});

Route::get('register', function(){
	return views('auth.register');
});

Auth::routes();
Route::get('/home', 'HomeController@index');

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class menu extends Model
{
    protected $fillable = ["title"];
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
          $menus = \App\Menu::all();
       return view('menus.index', compact('menus'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('menus.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
          $menus= \App\Menu::create($request->all());

        return redirect()->route('menus.index');

    }
    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
           $menu = \App\Menu::find($id);
            return view('menus.create', compact('menu')); 
            
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
          $menu = \App\Menu::find($id);
            return view('menus.create', compact('menu')); 
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        \App\Menu::find($id)->update($request->all());
        return redirect()->route('menus.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\Menu::find($id)->delete();
        return redirect()->route('menus.index');
    }
}

resources/views/menus/create.blade.php
@extends('layouts.app')
@include('layouts.header')
@section('content')



<div class="container">
<div class="row">
  @if(isset($menu))
 
    <form class="form-group forms" action="{{route('menus.update', $menu->id)}}" method="POST">
    
    <input type="hidden" name="_method" value="PUT">
    @else
    <form class="form-group" action="{{route('menus.store')}}" method="POST">
    @endif
        {{ csrf_field() }}

            <label for="name">Kategorijos pavadinimas</label>
            
            @if(isset($menu))
            <input value="{{ $menu->title }}" class="form-control" type="text" name="title">
            @else
            <input class="form-control" type="text" name="title">
            @endif
          
           
         
            <button class="btn btn-success" type="submit" name="submit">{{ isset($menu) ? 'Redaguoti' : 'Pridėti'}}</button>
 

    </form>
    @if(isset($menu))
    <form class="form-group" action="{{route('menus.destroy', $menu->id)}}" method="POST">
    {{ csrf_field() }}
    <input type="hidden" name="_method" value="DELETE">
        <button class="btn btn-danger">Ištrinti</button>
    </form>
    @endif

</div>   
</div>
@endsection

resources/views/menus/index.blade.php
@extends('layouts.app')
@include('layouts.header')
@section("content")

<div class="categories">
	<div class="container">
   
   
    <div class="row">
    <h1>Kategorijos</h1>
    @foreach($menus as $menu)
    <div class="col-md-4 col-sm-6 col-xs-12">      
      <a href="{{url('form/create')}}"><li>{{$menu->title}}</li></a>    
    </div>
    @endforeach
</div>  
</div>
</div>



@endsection