routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('/', function () {
	$menus = \App\Menu::all();
    return view('main', compact('menus'));


});

Route::get('contact', function(){
	return view('contacts.index');
});

Route::resource('/clients', 'ClientController');

Route::resource('/menus', 'MenuController');

Route::resource('/form', 'FormController');


Route::get('kategorijos', function(){
	return view('category');
});

Route::get('login', function(){
	return views('auth.login');
});

Route::get('register', function(){
	return views('auth.register');
});

Auth::routes();
Route::get('/home', 'HomeController@index');

app/Http/Controllers/FormController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class FormController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $form = \App\Client::all();
       return view('main', compact('form'));
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('form.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form= \App\Client::create($request->all());

        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
            $form = \App\Client::find($id);
            return view('form.create', compact('form')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         \App\Client::find($id)->update($request->all());
        return redirect('/');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \App\Client::find($id)->delete();
        return redirect()->route('form.index');
    }
}

resources/views/form/create.blade.php
@extends('layouts.app')
@include('layouts.header')
@section('content')


<div class="container">
    <div class="row">
    <div class="form-create">
  @if(isset($form))
    <form  action="{{route('form.update', $form->id)}}" method="POST">
    <input type="hidden" name="_method" value="PUT">
    @else
    <form  action="{{route('form.store')}}" method="POST">
    @endif
        {{ csrf_field() }}
       
            
            @if(isset($form))
            
            <input value="{{ $form->name }}" class="form-control" type="text" name="name" >
            @else
            <label for="name">Vardas</label>
            <input type="text" name="name" class="form-control" >
            @endif
            
      
            @if(isset($form))
            <input value="{{$form->email}}" class="form-control" type="text" name="email" >
            @else
             <label for="email">Elektroninis paštas</label>
            <input  type="text" class="form-control" name="email">
            @endif


               
            @if(isset($form))
            <input value="{{$form->phone}}" class="form-control" type="text" name="phone" >
            @else
            <label for="phone">Telefono numeris:</label>
            <input  type="text" class="form-control" name="phone">
            @endif

              @if(isset($form))
            <input value="{{$form->price}}" class="form-control" type="text" name="price" >
            @else
            <label for="price">Projekto kaina</label>
            <input  type="text" class="form-control" name="price">
            @endif


            @if(! isset($form))
             <label for="description">Norimos paslaugos aprašymas</label>
            <textarea  type="text" class="form-control" name="description" type="text" name="description"></textarea>
            @else

            <textarea class="form-control" value="{{$form->description}}" name="description"  rows="4" cols="50">{{$form->description}}</textarea>
            @endif

            <button  class="btn btn-success" type="submit" name="submit">{{ isset($form) ? 'Edit' : 'Siūsti'}}</button>

    </form>
    @if(isset($form))
    <form action="{{route('form.destroy', $form->id)}}" method="POST">
    {{ csrf_field() }}
    <input type="hidden" name="_method" value="DELETE">
        <button >Delete</button>
    </form>
    @endif

  </div>

</div>
</div>

@endsection